### ISSUE TITLE
Fails to build Samurai Shodown V Perfect

### ISSUE THREAD

**Issue by Yorper** [city41/neosdconv#3]
I know this is a very grey area for many people, it would be nice if this could build Samurai Shodown V Perfect.

It builds samsh5pf but not samsh5fe.

**Comment by city41** [comment]
Can you try now with the just published `0.1.6`?

It builds the rom and looks to be correct. However, I don't have access to my Neo or NeoSD right now as I just moved, so I was unable to test it.

**Comment by city41** [comment]
also I am out of the loop on ss5 perfect, what is the difference between `samsh5pf` and `samsh5fe`, @Yorper?

**Comment by Yorper** [comment]
There’s a nice discussion going on here:

http://www.neo-geo.com/forums/showthread.php?280394-Samurai-Shodown-V-Perfect-Final-Edition-extracted-data

Basically one is encrypted the other isnt. I’m working right now but will test and report back soon as I can.

**Comment by Yorper** [comment]
There’s a nice discussion going on here:

http://www.neo-geo.com/forums/showthread.php?280394-Samurai-Shodown-V-Perfect-Final-Edition-extracted-data

I’m working right now but will test and report back soon as I can.

**Comment by Yorper** [comment]
Ok, latest version of the tool builds both release. One just holds at a copy protection screen, the other boot loops at the NEO-GEO boot screen.

This is likely due to the extractions of the ROMs this early in the release. There may be some patching of the ROMs needed. I'll have to keep on reading up on the situation.

**Comment by city41** [comment]
In that thread they have fully running roms, but I suspect the two roms posted here are early dumps. If you could get a hold of a rom known to run, my hunch is neosdconv would build a correct neo file for it.

**Comment by Yorper** [comment]
It seems someone has released a full working and translated .neo file. I’ll delete the links above to prevent trash ROMs spreading around.

It would be nice if we could unpack the .neo for comparison. Feel free to mark this issue as closed.

https://drive.google.com/file/d/1S7v7mZNmwmWWX6u511eECPq4RoYQ0mvZ/view?usp=sharing

**Comment by Yorper** [comment]
I think you are totally right. For now there appears to be some activity on the French forums with a working .neo ready to go. Read more below.

https://www.neogeo-system.com/t7400p200-neosd-roms-neo#333744

It would be nice if this tool could extract .neo files too, so we can compare ROMs...

**Comment by city41** [comment]
I agree extracting .neo files would be nice. But I'm not sure if I want to take that on, at least right now. A big problem is the .neo file format is not well documented.

If the tool could extract .neo files, then it'd be possible to write a script that extracts an entire .neo rom set and confirms the extracted roms are correct, helping to confirm the tool implements the file format correctly.

But, with all that said, the real purpose of this tool is for homebrew devs who don't want to use Windows. So I am a bit hesitant to take all this on.

**Comment by city41** [comment]
neosdconv builds SS5 perfect correctly, and it always has. I suspect early roms were just not correct.

I am using samsh5pf.zip with sha cb27b2f1f51058b2d713546dadb8d16badfb5f3f

I acquired this rom on archive.org

![image](https://user-images.githubusercontent.com/141159/142018949-bccf2df2-0f64-4b66-9f6e-c7dd7e49f5ea.png)
