### ISSUE TITLE
Only able to pass subdirectory of PWD to -i and -o

### ISSUE THREAD

**Issue by kbembedded** [city41/neosdconv#4]
See lines here:
https://github.com/city41/neosdconv/blob/f027ae24122444bdf91591c7c966633ab77b13d0/src/index.ts#L36-L37

Joining cwd() to the args means that you can only process files in a subdirectory of the current directory rather than absolute path. This makes scripting this command difficult (I'm working on doing just that and ran in to this)

I don't speak node.js, but it looks like path.resolve() is the way to handle this here?

**Comment by city41** [comment]
Thanks for the report. You're correct, using `path.join` there was a bonehead mistake 😬 I changed it to `path.resolve` and published `0.2.1` with the fix. 

Fixed with 0fd5196c7daa72819fbf3e2c603372e8690e1da5

**Comment by kbembedded** [comment]
Thanks, I'll give it a try tonight!

FWIW it looks like the fix should work, but, I don't think its necessary to even pass cwd() to path.resolve() based on its description of operation: https://nodejs.org/api/path.html#path_path_resolve_paths It seems like path segments that are passed are eventually resolved against the current directory. Since it will return the last absolute path given to it, passing cwd() should be harmless, but I'm not sure if there are any other weird implications of doing that.

Thanks for making this tool, BTW. I've already had better success with this than the official tool which is why I'm working on a script to utilize this and have similar behavior to the official UI tool. Should have a PR available in the next week or so.
