### ISSUE TITLE
neosdconv doesn't seem to implement "parent" attribute in .neo file

### ISSUE THREAD

**Issue by kbembedded** [city41/neosdconv#5]
Still moving forward with a useful script (feel free to check out my fork for slow progress updates and such), and am starting to tackle ROM sets that are a hack and require a parent ROM.

Using Riding Hero as an example, I can see that the NeoBuilderUI tool dumps the ASCII name of the parent ROM starting at 0x6F:

```

00000000   4E 45 4F 01  00 00 08 00  00 00 02 00  00 00 04 00  00 00 10 00  00 00 20 00  00 00 20 00  C6 07 00 00  04 00 00 00  NEO................... ... .........
00000024   87 00 00 00  06 00 00 00  52 69 64 69  6E 67 20 48  65 72 6F 20  28 73 65 74  20 32 29 00  00 00 00 00  00 00 00 00  ........Riding Hero (set 2).........
00000048   00 00 00 00  00 53 4E 4B  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  .....SNK............................
0000006C   00 00 00 72  69 64 68 65  72 6F 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  ...ridhero..........................

```

The docs that come with NeoBuilder don't seem to call this out, i.e.:

```

    struct NeoFile
    {
        uint8_t header1, header2, header3, version;
        uint32_t PSize, SSize, MSize, V1Size, V2Size, CSize;
        uint32_t Year;
        uint32_t Genre;
        uint32_t Screenshot;
        uint32_t NGH;
        uint8_t Name[33];
        uint8_t Manu[17];
        uint8_t Filler[128 + 290];      //fill to 512
        uint8_t Filler2[4096 - 512];    //fill to 4096
    }


```

Filler starts at 0x5E or so.

I'm not sure if this is actually worth implementing considering a .neo file that's a hacked version more or less just replacing the minimum number of ROM files of the parent.

Back to Riding Hero, unpacking ridhero.zip and then ridheroh.zip, renaming the one file in ridheroh to match its corresponding ridhero name, then building it with neosdconv, is identical in the binary aside from the absent "parent" in the .neo header.

Mostly just opening this to document it.

**Comment by city41** [comment]
Thanks for documenting this. My main goal with neosdconv was for homebrew dev. I haven't put much thought at all into truly supporting the full commercial rom set.

But with that said, people seem to gradually be interested in neosdconv becoming a full replacement for TerraOnion's tool. So I have no problem with continuing in that direction.

Thanks for writing the shell script for bulk processing. It's looking good and will be really handy!

**Comment by city41** [comment]
I'm going to close this as "won't fix", as I don't think there is any actual benefit here. The user never sees the parent rom name in the NeoSD UI, and lacking the parent rom name seems to cause no harm. If anyone can find a purpose for this beyond matching NeoBuilder, I'm happy to reopen.
