### ISSUE TITLE
Neo Geo CD support

### ISSUE THREAD

**Issue by sreuter** [city41/neosdconv#9]
Hi @city41! I'm not sure if you considered this already in the past, but it would be awesome to get support for creating Neo Geo CD .neo files at some point, as mentioned here: https://wiki.terraonion.com/index.php/NeoSD_Pro_CD_Setup_Guide

I'm currently looking into adding CD support to our game, so this would me a massive help :)

**Comment by city41** [comment]
That would be awesome. But as far as I know, Terraonion and Razoola haven't released any info on how CD .neos are made. I doubt I'd be able to reverse engineer the process. I also think since they've only released 50 games so far, that might suggest the process varies a bit from game to game.
